version: "3"
services:
  broker:
    image: ghcr.io/d8-x/d8x-broker-server:main
    #build:
    #  context: .
    #  dockerfile: ./cmd/brokerapi/Dockerfile
    restart: always
    depends_on:
      - redis
    ports:
      # Default svc port is 8001
      - 127.0.0.1:8001:8001
    networks:
      - app-net
    environment:
      REDIS_ADDR: redis:6379
      REDIS_PW: "${REDIS_PW}"
      BROKER_FEE_TBPS: "${BROKER_FEE_TBPS}"
      CONFIG_PATH: /chain_config
      CONFIG_RPC_PATH: /rpc_config
      KEYFILE_PATH: /keyfile/
    logging:
      options:
        max-size: "10m"
        max-file: "10"
    configs:
      - chain_config
      - rpc_config
    volumes:
      - mydata:/keyfile

  executorws:
    image: ghcr.io/d8-x/d8x-broker-exec-ws:main
    #build:
    #  context: .
    #  dockerfile: ./cmd/executorws/Dockerfile
    restart: always
    depends_on:
      - redis
    ports:
      # Default svc port is 8080
      - 127.0.0.1:8080:8080
    networks:
      - app-net
    environment:
      REDIS_ADDR: redis:6379
      REDIS_PW: "${REDIS_PW}"
      WS_ADDR: "${WS_ADDR}"
      CONFIG_PATH: /chain_config
    logging:
      options:
        max-size: "10m"
        max-file: "10"
    configs:
      - chain_config

  redis:
    image: redis
    command: redis-server --requirepass ${REDIS_PW}
    environment:
      - TZ=UTC
      - REDIS_PASSWORD=${REDIS_PW}
    ports:
      - "127.0.0.1:6379:6379"
    networks:
      - app-net
    restart: on-failure
    logging:
      options:
        max-size: "10m"
        max-file: "10"

networks:
  app-net:

configs:
  chain_config:
    file: ./chainConfig.json
  rpc_config:
    file: ./rpc.json

volumes:
  mydata:
