version: "3"
services:
  broker:
    image: ghcr.io/d8-x/d8x-broker-server:main
    #build:
    #  context: .
    #  dockerfile: ./cmd/brokerapi/Dockerfile
    restart: always
    depends_on:
      - redis
    ports:
      # Default svc port is 8001
      - 127.0.0.1:8001:8001
    networks:
      - app-net
    environment:
      REDIS_ADDR: redis:6379
      REDIS_PW: "${REDIS_PW}"
      BROKER_FEE_TBPS: "${BROKER_FEE_TBPS}"
      CONFIG_PATH: /chain_config
      KEYFILE_PATH: /keyfile/
    logging:
      options:
        max-size: "10m"
        max-file: "10"
    configs:
      - chain_config
    volumes:
      - keyvol:/keyfile
    env_file:
      - path: .env
        required: false
  executorws:
    image: ghcr.io/d8-x/d8x-broker-exec-ws:main
    #build:
    #  context: .
    #  dockerfile: ./cmd/executorws/Dockerfile
    restart: always
    depends_on:
      - redis
    ports:
      # Default svc port is 8080
      - 127.0.0.1:8080:8080
    networks:
      - app-net
    environment:
      REDIS_ADDR: redis:6379
      REDIS_PW: "${REDIS_PW}"
      WS_ADDR: "${WS_ADDR}"
      CONFIG_PATH: /chain_config
    logging:
      options:
        max-size: "10m"
        max-file: "10"
    configs:
      - chain_config
    env_file:
      - path: .env
        required: false

  rpc-proxy:
    image: ghcr.io/d8-x/d8x-rpc-proxy:main
    restart: always
    depends_on:
      - redis
    ports:
      - ${BROKER_PRIVATE_IP:-127.0.0.1}:8090:8080
    networks:
      - app-net
    environment:
      CHAIN_ID: "${CHAIN_ID}"
      RPC_CONFIG_FILE: /rpc_config
      PRIVY_APP_ID: "${PRIVY_APP_ID}"
      RATE_LIMIT: "${RATE_LIMIT}"
      ENFORCE_MODE: "${ENFORCE_MODE}"
      REDIS_ADDR: redis:6379
      REDIS_PASSWORD: "${REDIS_PW}"
    logging:
      options:
        max-size: "10m"
        max-file: "10"
    configs:
      - rpc_config

  redis:
    image: redis
    command: redis-server --requirepass ${REDIS_PW}
    environment:
      - TZ=UTC
      - REDIS_PASSWORD=${REDIS_PW}
    ports:
      - "127.0.0.1:6379:6379"
    networks:
      - app-net
    restart: on-failure
    logging:
      options:
        max-size: "10m"
        max-file: "10"

networks:
  app-net:

configs:
  chain_config:
    file: ./chainConfig.json
  rpc_config:
    file: ./rpc.json

volumes:
  keyvol:
    external: true
