{
 "title": "D8X Services",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  { "title": "Resources", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Services CPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 19, "w": 11, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(sum(rate(container_cpu_usage_seconds_total{container_label_com_docker_swarm_service_name!=\"\"}[5m])) BY  (container_label_com_docker_swarm_service_name, instance) * 100)",
     "legendFormat": "{{container_label_com_docker_swarm_service_name}} ({{instance}}) "
    }
   ]
  },
  {
   "title": "Services RAM Usage",
   "type": "timeseries",
   "gridPos": { "h": 19, "w": 12, "x": 11, "y": 1 },
   "targets": [
    {
     "expr": "container_memory_rss{container_label_com_docker_swarm_service_name!=\"\"}/(1024^2)",
     "legendFormat": "{{container_label_com_docker_swarm_service_name}} ({{instance}})"
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "Network I/O (Transmitted)",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 23, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "rate(container_network_transmit_bytes_total{container_label_com_docker_swarm_service_name!=\"\"}[5m]) / 1024^2",
     "legendFormat": "{{container_label_com_docker_swarm_service_name}} ({{instance}})"
    }
   ]
  },
  {
   "title": "Network I/O (Received)",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 23, "x": 0, "y": 33 },
   "targets": [
    {
     "expr": "rate(container_network_receive_bytes_total{container_label_com_docker_swarm_service_name!=\"\"}[5m]) / 1024^2",
     "legendFormat": "{{container_label_com_docker_swarm_service_name}} ({{instance}})"
    }
   ]
  }
 ]
}