apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    url: http://prometheus:9090
    access: proxy
    basicAuth: false
    isDefault: true
    version: 1
    editable: true
    # Make sure this matches uid's in charts
    uid: PBFA97CFB590B2093