version: "3.8"
services:
  redis:
    image: redis/redis-stack-server:latest
    command: redis-stack-server --requirepass ${REDIS_PASSWORD}
    environment:
      - TZ=UTC
    logging:
      driver: "json-file"
      options:
        max-size: "1k"
        max-file: "10"
    networks:
      - d8x_backend
    deploy:
      replicas: 1
      # placement:
      # constraints:
      # Always run redis on the same node
      # - "node.hostname==worker-1"
  api:
    image: ghcr.io/d8-x/d8x-trader-main:dev
    ports:
      # REST API
      - ${MAIN_API_PORT_HTTP:-3001}:${MAIN_API_PORT_HTTP:-3001}
      # Websockets port
      - ${MAIN_API_PORT_WEBSOCKET:-3002}:${MAIN_API_PORT_WEBSOCKET:-3002}
    environment:
      - BROKER_KEY=${BROKER_KEY}
      - BROKER_FEE_TBPS=${BROKER_FEE_TBPS}
      - REMOTE_BROKER_HTTP=${REMOTE_BROKER_HTTP}
      - REDIS_URL=${REDIS_URL:-redis://:thisismypassword@redis:6379/0}
      - CHAIN_ID=${CHAIN_ID:-80001}
      - SDK_CONFIG_NAME=${SDK_CONFIG_NAME:-testnet}
      - CORS_ON=${CORS_ON:-FALSE}
      - MAIN_API_PORT_HTTP=${MAIN_API_PORT_HTTP:-3002}
      - MAIN_API_PORT_WEBSOCKET=${MAIN_API_PORT_WEBSOCKET:-3002}
      - CONFIG_PATH_RPC=/cfg_rpc
      - CONFIG_PATH_REFERRAL_SETTINGS=/cfg_referral
    networks:
      - d8x_backend
    deploy:
      replicas: 2
    configs:
      - cfg_rpc
      - cfg_referral
  history:
    image: ghcr.io/d8-x/d8x-trader-history:dev
    environment:
      - DATABASE_DSN_HISTORY=${DATABASE_DSN_HISTORY}
      - HISTORY_API_PORT_HTTP=${HISTORY_API_PORT_HTTP:-3003}
      - SDK_CONFIG_NAME=${SDK_CONFIG_NAME}
      - CHAIN_ID=${CHAIN_ID}
      - CORS_ON=${CORS_ON:-FALSE}
      - CONFIG_PATH_RPC=/cfg_rpc
      - CONFIG_PATH_REFERRAL_SETTINGS=/cfg_referral
    ports:
      - "${HISTORY_API_PORT_HTTP:-3003}:${HISTORY_API_PORT_HTTP:-3003}"
    logging:
      driver: "json-file"
      options:
        max-size: "5000k"
        max-file: "10"
    deploy:
      replicas: 1
    configs:
      - cfg_rpc
      - cfg_referral
    networks:
      - d8x_backend
  referral:
    image: ghcr.io/d8-x/d8x-trader-referral:dev
    deploy:
      # Restart 3 times with 30 seconds delay before giving up.
      restart_policy:
        condition: any
        delay: 30s
        max_attempts: 3
        # Do not wait to verify restart
        window: 0s
    environment:
      - REDIS_URL=${REDIS_URL:-redis://:thisismypassword@redis:6379/0}
      - DATABASE_DSN_REFERRAL=${DATABASE_DSN_REFERRAL}
      - REFERRAL_API_PORT_HTTP=${REFERRAL_API_PORT_HTTP:-3004}
      - BROKER_KEY=${BROKER_KEY}
      - REMOTE_BROKER_HTTP=${REMOTE_BROKER_HTTP}
      - CHAIN_ID=${CHAIN_ID}
      - CORS_ON=${CORS_ON:-FALSE}
      - HISTORY_API_ENDPOINT="http://history:${HISTORY_API_PORT_HTTP:-3003}"
      - CONFIG_PATH_RPC=/cfg_rpc
      - CONFIG_PATH_REFERRAL_SETTINGS=/cfg_referral
    ports:
      - "${REFERRAL_API_PORT_HTTP:-3004}:${REFERRAL_API_PORT_HTTP:-3004}"
    logging:
      driver: "json-file"
      options:
        max-size: "5000k"
        max-file: "10"
    configs:
      - cfg_rpc
      - cfg_referral
      - source: pg_ca
        target: /pg.crt
    networks:
      - d8x_backend

  candles-pyth-client:
    image: ghcr.io/d8-x/d8x-candles-pyth-client:main
    environment:
      - REDIS_PW=${REDIS_PASSWORD}
      - REDIS_ADDR=redis:6379
      # Use different database tha
      - REDIS_DB_NUM=0
      - CONFIG_PATH=/cfg_candles
    networks:
      - candles
      - d8x_backend
    logging:
      options:
        max-size: "10m"
        max-file: "10"
    configs:
      - cfg_candles
    deploy:
      replicas: 1

  # Candles websockets server
  candles-ws-server:
    image: ghcr.io/d8-x/d8x-candles-ws-server:main
    ports:
      - 3005:8080
    environment:
      - REDIS_PW=${REDIS_PASSWORD}
      - REDIS_ADDR=redis:6379
      # Use different database tha
      - REDIS_DB_NUM=0
      - CONFIG_PATH=/cfg_candles
      - WS_ADDR=0.0.0.0:8080
    networks:
      - candles
      - d8x_backend
    logging:
      options:
        max-size: "10m"
        max-file: "10"
    configs:
      - cfg_candles
    deploy:
      replicas: 1

networks:
  d8x_backend:
    driver: overlay
    name: d8x_backend
  candles:
    driver: overlay
configs:
  cfg_rpc:
    external: true
  cfg_referral:
    external: true
  pg_ca:
    external: true
  cfg_candles:
    external: true
