services:
  prometheus: 
    image: prom/prometheus:v2.47.2
    ports:
      - 4001:9090
    deploy:
      placement:
        constraints:
          - "node.hostname==manager-1"
    configs:  
      - source: prometheus_config
        target: /etc/prometheus/prometheus.yml
    volumes:
      - prometheus_data_vol:/prometheus
    networks:
      - metrics_net
  grafana: 
    image: grafana/grafana
    ports:
      - 4002:3000
    deploy:
      placement:
        constraints:
          - "node.hostname==manager-1"
    volumes:  
      # Default prometheus service data source
      - ./grafana/datasource-prometheus.yml:/etc/grafana/provisioning/datasources/prometheus.yml
      # Dashboards config
      - ./grafana/dashboards.yml:/etc/grafana/provisioning/dashboards/dashboards.yml
      # Default dashboard
      - ./grafana/chart.json:/var/lib/grafana/dashboards/chart.json
      # Persistence for grafana
      - 'grafana_data:/var/lib/grafana'
    networks:
      - metrics_net
configs:
  prometheus_config:
    external: true
volumes:  
  prometheus_data_vol:  
    external: true
  grafana_data:
networks:
  metrics_net:
    driver: overlay