scrape_configs:
  # Make Prometheus scrape itself for metrics.
  - job_name: 'prometheus'
    static_configs:
    - targets: ['localhost:9090']
  - job_name: 'swarm-nodes-cadvisor'
    static_configs:
      - targets:
        - '10.0.1.31:8080'
        - '10.0.1.245:8080'
        - '10.0.1.39:8080'
        - '10.0.1.26:8080'
