scrape_configs:
  # Make Prometheus scrape itself for metrics.
  - job_name: 'prometheus'
    static_configs:
    - targets: ['localhost:9090']
  - job_name: 'swarm-service'
    dns_sd_configs:
      - names:
          - 'tasks.cadvisor'
        type: 'SRV'
        port: 8080