name: Build images
on:
  push:
    branches: ["main", "dev"]
    tags: "*"
jobs:
  build:
    permissions:
      contents: read
      packages: write
    strategy:
      fail-fast: false
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21"
      - name: Get Time
        id: time
        uses: nanzm/get-time-action@master
        with:
          timeZone: UTC
          format: "YYYY-MM-DD HH-mm-ss"
      - name: Build D8X CLI
        run: |
          go build -o d8x \ 
            -ldflags="-X 'github.com/D8-X/d8x-cli/internal/version.commit=${{ github.ref }}'"\
            -ldflags="-X 'github.com/D8-X/d8x-cli/internal/version.buildTime=${{ steps.time.outputs.time }}'"\
            main.go
