name: Build images
on:
  push:
    branches: ["main", "dev"]
    tags: "*"
jobs:
  build:
    permissions:
      contents: read
      packages: write
    strategy:
      fail-fast: false
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21"
      - name: Build
        run: |
          go build -o d8x -ldflags="-X 'github.com/D8-X/d8x-cli/internal/version.commit=test'" main.go
