name: Test on push
on:
  push:
    branches: "*"
jobs:
  build:
    permissions:
      contents: write
      packages: write
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21"
      - name: Get Time
        id: time
        uses: nanzm/get-time-action@master
        with:
          timeZone: UTC
          format: "YYYY-MM-DD HH-mm-ss"
      - name: Run tests
        run: go test ./...
